"""empty message

Revision ID: 1a95af468563
Revises: e7a5cf4201c6
Create Date: 2020-03-10 10:27:02.486459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a95af468563'
down_revision = 'e7a5cf4201c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('country', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'country')
    # ### end Alembic commands ###
