"""empty message

Revision ID: e7a5cf4201c6
Revises: 823b7933359c
Create Date: 2020-03-10 10:09:23.664943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a5cf4201c6'
down_revision = '823b7933359c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('owner', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'owner')
    # ### end Alembic commands ###
